### ISSUE TITLE
plugin can not connect with connector apps

### ISSUE THREAD

**Issue by jeonjhong** [gormanb/homebridge-connector-hub#13]
**Describe The Bug:**
after put app-key of connector app, it can not connect my curtain

**To Reproduce:**

**Expected behavior:**

**Logs:**

[7/21/2023, 5:56:57 PM] [homebridge-connector-hub] Failed to reach 238.0.0.18, retry in 5000ms
[7/21/2023, 5:57:02 PM] [homebridge-connector-hub] Failed to reach 238.0.0.18, retry in 5000ms

**Plugin Config:**

{
            "hubIps": [],
            "connectorKey": "",
            "enableDebugLog": false,
            "platform": "ConnectorHub",
            "_bridge": {
                "username": "",
                "port": 
            }
}
**Screenshots:**

**Environment:**
homebridge in macbook pro m1
and using connector+ app with curtain and hub
* **Plugin Version**:
* 1.0.9
* **Homebridge Version**: 
* 1.6.1
* **Node.js Version**: 
* [v20.3.1]
* **NPM Version**: 
* 9.6.7
* **Operating System**
* mac m1

**Comment by gormanb** [comment]
Hi @jeonjhong - I notice that the IP the plugin is trying to contact is 238.0.0.18, i.e. the multicast address used for auto-discovery of devices. In some environments, it's not possible for the plugin to reach this address; please try entering the actual IP address of your hub/device into the config UI so that the plugin can attempt to connect directly to it, and see if that solves the problem.

**Comment by gormanb** [comment]
Hi @jeonjhong - any update on this? Were you able to connect to your devices successfully?

**Comment by jeonjhong** [comment]
Yes. I found my real ip for device via wifi router   
thank you for advice. And close this issue
