### ISSUE TITLE
Reverse feature

### ISSUE THREAD

**Issue by ToracX** [gormanb/homebridge-connector-hub#20]
Hi,

Could you maybe add a reverse feature?

**Comment by gormanb** [comment]
Hi @ToracX - you mean an option to reverse the direction of the blinds associated with a particular hub? Are you having a problem where your blinds move in the opposite direction to what you request in the Home app?

**Comment by ToracX** [comment]
Yes so basically when the app says open they are closed and vice versa. Using motion blinds with the CM20 hub from Hornbach.

**Comment by gormanb** [comment]
Could you please do the following, so that I have some more information about the blinds:
- Enable Debug Logging in the plugin config
- Restart Homebridge so the setting takes effect
- The logs should start printing a lot of information. Please try to open and then close one of the blinds whose direction is reversed, so that both operations are captured in the logs.
- Post the resulting logs here. You can then disable Debug Logging and restart Homebridge again.

**Comment by ToracX** [comment]
Yes I got it fixed now. Something you might want to think of:

When changing directions, while the blind is either closing or opening, it will stop instead of moving. 

You could fix this by adding a stop before moving to the changed position. So check for reverse direction then sending a blinds stop then blinds set position. 

So for instance blind is at 20% and set position is 80% it is moving going from 20->80, now its not yet at 80 and I decide I want it closed or 0%, now the blind just stops there and doesnt move anymore. Gets out of sync and only gets the actual position when sending a get handler again.
