### ISSUE TITLE
Periodic Refresh interval 

### ISSUE THREAD

**Issue by cameronf762** [gormanb/homebridge-connector-hub#22]
Is it possible to look at a setting to change the interval of the periodic refresh? Since linking to home bridge I have found that my blinds which run on battery packs seem to be going flat much quicker. 

Awesome app though! The provided controller and app are terrible UI so it is great to have this homebridge plugin to pull it into Apple Home, and Google Home :)

**Comment by gormanb** [comment]
Hi @cameronf762 - many thanks for the kind words, I'm glad you're finding the plugin useful 😄 

The periodic refreshes only read cached data from the hub, so they shouldn't be taxing the batteries of the blinds themselves. Have you by any chance been using [v1.0.8](https://github.com/gormanb/homebridge-connector-hub/releases/tag/v1.0.8)? That introduced once-per-minute "active reads" to sync certain values that the hub does not cache, but I found that it reduced my blinds' battery life from months to weeks. From [v1.0.9](https://github.com/gormanb/homebridge-connector-hub/releases/tag/v1.0.9) onwards, I've reduced the frequency of active reads to once per hour. Since then, I've had no problems with my blinds' batteries 😄
