### ISSUE TITLE
Ublockout plugin config

### ISSUE THREAD

**Issue by michaelklachko** [gormanb/homebridge-connector-hub#30]
Hi, 

I got here from https://my.ublockout.com/?faq=MT-03 where they say I need to do the following:

1. Ensure Homebridge is installed
    [View how to install Homebridge for your device](https://github.com/homebridge/homebridge/wiki)
2. Search for the plugin
    Open the plug-in [homebridge-connector-hub](https://github.com/gormanb/homebridge-connector-hub) (v1.1.3).
3. Install the plugin
    Open your terminal or command prompt and run the following command:

npm install -g homebridge-connector-hub

4. Configure the plugin
        Edit your Homebridge config.json file.
        Add the plugin to the "platforms" section with its required configuration.
        For example:

    "platforms": [
         { "platform": "homebridge-connector-hub",
                  "key1": "value1",
                  "key2": "value2" 
          }
    ],
    
    
I got as far as step 4, however, I don't know what is the "required configuration" of the plugin, and what to use instead of key1 and key2 values. I see "App Key" mentioned in the Readme for this repo, but I don't quite get what is the exact key name, and whether there are any other fields to fill out. Where can I find an example of such config, or any info about it?

Thanks, and sorry if it's a dumb question and I'm missing something obvious.

**Comment by gormanb** [comment]
Hi @michaelklachko! The config for the plugin is as follows:

```
{
    "connectorKey": "key_from_blinds_app",
    "hubIps": [
        "ip_of_hub"
    ],
    "invertReverseList": false,
    "maxRetries": 2,
    "retryDelayMs": 250,
    "enableDebugLog": false,
    "platform": "ConnectorHub"
}
```

The only thing you really need to provide is the `connectorKey` from your blinds app, and the IP of your hub or device. The latter isn't strictly necessary since the plugin will attempt to auto-detect your hub if you set `"hubIps": []`, but depending on your network setup this doesn't always work. The other fields can be left as they are.

As an aside, if you don't already have it you should consider installing the [Homebridge UI](https://github.com/homebridge/homebridge-config-ui-x), which allows you to install and configure plugins via a web UI - much easier than editing the config manually!

**Comment by gormanb** [comment]
Hey @michaelklachko - did the above solve your problem?

**Comment by gormanb** [comment]
Closing this issue, but feel free to reopen if you need more help!
